version: '3.8'

services:
    ewelink-proxy-server:
        build: .
        image: ewelinkproxyserver
        container_name: ewelink-proxy-server
        restart: always
        ports:
            - "8000:80/tcp"
        environment:
            - EWELINK_EMAIL=<YOUR_EWELINK_EMAIL>
            - EWELINK_PASSWORD=<YOUR_EWELINK_PASSWORD>
            - EWELINK_COUNTRY_CODE=<YOUR_EWELINK_COUNTRY_CODE>
            - EWELINK_REGION=<YOUR_EWELINK_REGION>
            - EWELINK_APP_ID=<YOUR_EWELINK_APP_ID>
            - EWELINK_APP_SECRET=<YOUR_EWELINK_APP_SECRET>
